### ISSUE TITLE
Package vulnerability with diff

### ISSUE THREAD

**Issue by kevinkace** [namuol/tap-difflet#12]
I'm getting an warning from GH that there's a security concern with `diff`, a dependency of `tap-diff` through `ansidiff` (which looks to be abandoned).

Any way to get this resolved?

**Comment by namuol** [comment]
Can you send a screenshot? I don't see any security warnings on this repo specifically, which suggests it's not actually the `tap-difflet` repo that's hitting the insecure package in your setup (but I could be wrong!)

**Comment by kevinkace** [comment]
The issue was with `diff`, but now I can't see an issue with any of the packages! Sorry for the excitement!
